name: learn-github-actions
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Linterine
      - uses: actions/checkout@v3
      - run: az bicep build --file iac/bicep/main.bicep
